name: fd20
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  audioplayers: ^0.10.0

  # audioplayers: ^0.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/
    - images/
  
  # fonts:
  #   - family: LeonSans
  #     fonts:
  #       - asset: fonts/LeonSans-Regular.otf
  #         weight: 400
  #       - asset: fonts/LeonSans-Medium.otf
  #         weight: 500
  #       - asset: fonts/LeonSans-Bold.otf
  #         weight: 700

